name: hafez_poems
description: "Poems of Hafez"
publish_to: "none"
version: 2.5.8+11

environment:
  sdk: ^3.12.2

dependencies:
  carousel_slider: ^5.1.2
  flutter:
    sdk: flutter
  get: ^4.7.3
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2
  image_cropper: ^12.2.1
  path_provider: ^2.1.4
  path: ^1.9.0
  package_info_plus: ^10.1.0
  timezone: ^0.11.0
  permission_handler: ^12.0.1
  crop_your_image: ^2.0.0
  share_plus: ^13.1.0
  url_launcher: ^6.3.2
  http: ^1.6.0
  cupertino_icons: ^1.0.9
  collection: ^1.19.1
  connectivity_plus: ^7.1.1
  audio_session: ^0.2.3
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  xml: ^7.0.1
  video_player: ^2.11.1
  drift: ^2.34.1
  drift_flutter: ^0.3.0
  auto_size_text: ^3.0.0
  dio: ^5.10.0
  crypto: ^3.0.7
  lottie: ^3.5.1
  flutter_lucide_animated: ^0.0.4
  awesome_notifications: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.15.0
  drift_dev: ^2.34.2+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/hafez-logo.png"
  min_sdk_android: 21
  remove_alpha_ios_icons: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/badge/
    - assets/videos/
    - assets/audio/
    - assets/sounds/
    - assets/icons/
    - assets/icons/animatedIcons/
    - assets/json/

  fonts:
    - family: morvarid
      fonts:
        - asset: fonts/morvarid.ttf
    - family: vazir
      fonts:
        - asset: fonts/vazir.ttf
    - family: iran
      fonts:
        - asset: fonts/iran.ttf
    - family: iranrounded
      fonts:
        - asset: fonts/iranrounded.ttf
    - family: mahbobe
      fonts:
        - asset: fonts/mahbobe.ttf
    - family: hoda
      fonts:
        - asset: fonts/hoda.ttf
    - family: roosta
      fonts:
        - asset: fonts/roosta.ttf
